# Generated by Django 4.1.7 on 2023-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleeWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
    ]
